from core.exception.aborted_exception import AbortedException